import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.evomaster.client.java.sql.dsl.SqlDsl.sql;
import  org.evomaster.client.java.controller.api.dto.database.operations.InsertionResultsDto;
import  org.evomaster.client.java.controller.api.dto.database.operations.InsertionDto;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-02-12T17:20:05.743-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 46 tests
 * <br>
*  Covered targets: 993
 * <br>
*  Used time: 0h 29m 39s
 * <br>
*  Needed budget for current results: 91%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_faults_Test {

    
    private static final SutHandler controller = new em.embedded.market.EmbeddedEvoMasterController();
    private static String baseUrlOfSut;
    
    
    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @Before
    public void initTest() {
        controller.resetDatabase(Arrays.asList("CART","CONTACTS","CUSTOMER_ORDER","PRODUCT","USER_ACCOUNT","USER_ROLE","cart"));
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (500) POST:/register
    * Found 2 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_0_postOnRegisterShowsFaults_100_200() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 209L)
                .d("ID", "65536")
                .d("USER_ACCOUNT_ID", "952")
                .d("DATE_CREATED", "\"2016-12-04\"")
                .d("EXECUTED", "false")
                .d("PRODUCTS_COST", "NULL")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "8996")
            .and().insertInto("CART", 210L)
                .d("TOTAL_ITEMS", "827")
                .d("PRODUCTS_COST", "1024")
                .d("DELIVERY_INCLUDED", "true")
            .and().insertInto("CONTACTS", 211L)
                .d("PHONE", "\"q>8\"")
                .d("ADDRESS", "\"UcUkUtaUW\"")
                .d("CITY_REGION", "\"WO7w6ZR8NH\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault100. HTTP Status 500. market/rest/exception/RestErrorResponse_50_getFieldErrors POST:/register
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/register -> Response status 500 not defined for path '/register'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"_links\": [ " + 
                    " { " + 
                    " \"href\": \"3Ivyx0H\", " + 
                    " \"hreflang\": \"\", " + 
                    " \"name\": \"vEtxZEraUfL3UgvB\", " + 
                    " \"title\": \"mWBFgDTrb3euLTJ\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"qibFFq1_ZWNq6bH\", " + 
                    " \"href\": \"8gOxI\", " + 
                    " \"hreflang\": \"6jSBplEsy\", " + 
                    " \"media\": \"4E01grjj_82lK\", " + 
                    " \"name\": \"oP7GTQDknW4iXX\", " + 
                    " \"profile\": \"hk70IZwEnWo1\", " + 
                    " \"rel\": { " + 
                    " \"EM_tainted_map\": \"_EM_2_XYZ_\" " + 
                    " }, " + 
                    " \"title\": \"qmhr2cd0xuN_u\", " + 
                    " \"type\": \"k9_2r\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"J7w0X\", " + 
                    " \"href\": \"WFIbbjE3RbbfA\", " + 
                    " \"hreflang\": \"EWSBBpO5QxGXzq\", " + 
                    " \"media\": \"u1ngyN1x0oN\", " + 
                    " \"name\": \"GO\", " + 
                    " \"profile\": \"Lw89XBRgW\" " + 
                    " } " + 
                    " ], " + 
                    " \"email\": \"1OEcnlbW\" " + 
                    " } ")
                .post(baseUrlOfSut + "/register")
                .then()
                .statusCode(500)// market/rest/exception/RestErrorResponse_50_getFieldErrors
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("JSON parse error: Expected relation name; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Expected relation name\n at [Source: (ByteArrayInputStream); line: 1, column: 13] (through reference chain: market.dto.UserDTO[\"_links\"])"))
                .body("'description'", containsString("uri=/register"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/customer/contacts
    * Found 2 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_1_putOnContactsShowsFaults_100_200() throws Exception {
        
        // Fault100. HTTP Status 500. market/rest/exception/RestErrorResponse_50_getFieldErrors PUT:/customer/contacts
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/contacts -> Response status 500 not defined for path '/customer/contacts'.
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "_EM_325_XYZ_")
                .contentType("application/json")
                .body(" { " + 
                    " \"_links\": [ " + 
                    " { " + 
                    " \"deprecation\": \"zqi2b\", " + 
                    " \"hreflang\": \"http://localhost:63538/products/4\", " + 
                    " \"name\": \"C29tffsSJZZd59km\", " + 
                    " \"type\": \"3M2Rw325\" " + 
                    " }, " + 
                    " { " + 
                    " \"hreflang\": \"8\", " + 
                    " \"profile\": \"nNuI3Msimt\", " + 
                    " \"title\": \"GMbrrO1\", " + 
                    " \"type\": \"_EM_315_XYZ_\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"_EM_316_XYZ_\", " + 
                    " \"href\": \"_EM_317_XYZ_\", " + 
                    " \"hreflang\": \"gA9\", " + 
                    " \"profile\": \"a\", " + 
                    " \"rel\": { " + 
                    " \"EM_tainted_map\": \"_EM_1_XYZ_\" " + 
                    " }, " + 
                    " \"title\": \"6p5Va\", " + 
                    " \"type\": \"_EM_319_XYZ_\" " + 
                    " }, " + 
                    " { " + 
                    " \"href\": \"_EM_321_XYZ_\", " + 
                    " \"name\": \"aLGAp0NNLgg\", " + 
                    " \"profile\": \"_EM_324_XYZ_\", " + 
                    " \"rel\": { " + 
                    " \"EM_tainted_map\": \"_EM_1_XYZ_\" " + 
                    " }, " + 
                    " \"type\": \"cj5t9s1bZj2IpZ\" " + 
                    " } " + 
                    " ] " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/contacts?EMextraParam123=42")
                .then()
                .statusCode(500)// market/rest/exception/RestErrorResponse_50_getFieldErrors
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("JSON parse error: Expected relation name; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Expected relation name\n at [Source: (ByteArrayInputStream); line: 1, column: 13] (through reference chain: market.dto.ContactsDTO[\"_links\"])"))
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/customer/contacts
    * Found 2 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_2_putOnContactsShowsFaults_100_200() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 209L)
                .d("ID", "65536")
                .d("USER_ACCOUNT_ID", "952")
                .d("DATE_CREATED", "\"2016-12-04\"")
                .d("EXECUTED", "true")
                .d("PRODUCTS_COST", "NULL")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "8996")
            .and().insertInto("CART", 210L)
                .d("TOTAL_ITEMS", "827")
                .d("PRODUCTS_COST", "1024")
                .d("DELIVERY_INCLUDED", "true")
            .and().insertInto("CONTACTS", 211L)
                .d("PHONE", "\"q>8\"")
                .d("ADDRESS", "\"UcUkUtaUW\"")
                .d("CITY_REGION", "\"WO7w6ZR8NH\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault100. HTTP Status 500. market/rest/exception/RestErrorResponse_50_getFieldErrors PUT:/customer/contacts
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/contacts -> Response status 500 not defined for path '/customer/contacts'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"_links\": [ " + 
                    " { " + 
                    " \"href\": \"GBLECDvHqdCK\", " + 
                    " \"hreflang\": \"s\", " + 
                    " \"media\": \"cCXQjNO\", " + 
                    " \"name\": \"PR4G4\", " + 
                    " \"profile\": \"N4rg\", " + 
                    " \"title\": \"3gUKxGTORu7n\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"70lAVBv\", " + 
                    " \"media\": \"oJ1RPYthB\", " + 
                    " \"profile\": \"bM3Ha\", " + 
                    " \"title\": \"4h\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"xzC4\", " + 
                    " \"hreflang\": \"0YoAmE7BVYY\", " + 
                    " \"name\": \"yL0KSl8TYs\", " + 
                    " \"profile\": \"tTDsKdHlyElvaF\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"vLyqdQOtI7Ay\", " + 
                    " \"href\": \"p0DeQvJ_\", " + 
                    " \"name\": \"PO4oQ0\", " + 
                    " \"title\": \"9vo5M8pAjL69v_s\" " + 
                    " }, " + 
                    " { " + 
                    " \"hreflang\": \"2uWzubpgJ\", " + 
                    " \"profile\": \"eHJS\", " + 
                    " \"rel\": { " + 
                    " \"EM_tainted_map\": \"_EM_1_XYZ_\" " + 
                    " } " + 
                    " } " + 
                    " ], " + 
                    " \"address\": \"a\", " + 
                    " \"phone\": \"\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/contacts?name=_EM_1537_XYZ_")
                .then()
                .statusCode(500)// market/rest/exception/RestErrorResponse_50_getFieldErrors
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("JSON parse error: Expected relation name; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Expected relation name\n at [Source: (ByteArrayInputStream); line: 1, column: 13] (through reference chain: market.dto.ContactsDTO[\"_links\"])"))
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/customer/contacts
    * Found 2 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_3_putOnCustomerContactsWithQueryParamsShowsFaults_100_200() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("USER_ROLE", 870L)
                .d("USER_ID", "-8012762510440257536")
                .d("ROLE_ID", "659")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault100. HTTP Status 500. market/rest/exception/RestErrorResponse_50_getFieldErrors PUT:/customer/contacts
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/contacts -> Response status 500 not defined for path '/customer/contacts'.
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"_links\": [], " + 
                    " \"phone\": \"_postfix\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/contacts?" + 
                    "name=GbnTDuzxSpLc3&" + 
                    "included=qzMWv3D4Rx")
                .then()
                .statusCode(500)// market/rest/exception/RestErrorResponse_50_getFieldErrors
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("JSON parse error: Expected relation name; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Expected relation name\n at [Source: (ByteArrayInputStream); line: 1, column: 13] (through reference chain: market.dto.ContactsDTO[\"_links\"])"))
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/customer/cart
    * Found 2 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_4_putOnCartShowsFaults_100_200() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("USER_ROLE", 305L)
                .d("USER_ID", "NULL")
                .d("ROLE_ID", "NULL")
            .and().insertInto("CONTACTS", 306L)
                .d("PHONE", "\"TuxGgo_GwMRF\"")
                .d("ADDRESS", "NULL")
                .d("CITY_REGION", "\"RsyoACJ_qS\"")
            .and().insertInto("CART", 663L)
                .d("TOTAL_ITEMS", "107")
                .d("PRODUCTS_COST", "88")
                .d("DELIVERY_INCLUDED", "true")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault100. HTTP Status 500. market/rest/exception/RestErrorResponse_50_getFieldErrors PUT:/customer/cart
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart -> Response status 500 not defined for path '/customer/cart'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"_links\": [], " + 
                    " \"productId\": 6625979567330321392 " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/cart?" + 
                    "name=RfGl9WNoAKud06&" + 
                    "included=_EM_3502_XYZ_")
                .then()
                .statusCode(500)// market/rest/exception/RestErrorResponse_50_getFieldErrors
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("JSON parse error: Expected relation name; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Expected relation name\n at [Source: (ByteArrayInputStream); line: 1, column: 13] (through reference chain: market.dto.CartItemDTO[\"_links\"])"))
                .body("'description'", containsString("uri=/customer/cart"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (500) GET:/customer/contacts
    * Found 2 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_5_getOnContactsShowsFaults_100_200() throws Exception {
        
        // Fault100. HTTP Status 500. market/dto/assembler/ContactsDtoAssembler_12_toModel GET:/customer/contacts
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/contacts -> Response status 500 not defined for path '/customer/contacts'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/customer/contacts")
                .then()
                .statusCode(500)// market/dto/assembler/ContactsDtoAssembler_12_toModel
                .assertThat()
                .contentType("application/json")
                .body("'message'", nullValue())
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (500) GET:/customer
    * Found 2 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_6_getOnCustomerShowsFaults_100_200() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 209L)
                .d("ID", "65536")
                .d("USER_ACCOUNT_ID", "952")
                .d("DATE_CREATED", "\"2016-12-04\"")
                .d("EXECUTED", "true")
                .d("PRODUCTS_COST", "NULL")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "8996")
            .and().insertInto("CART", 210L)
                .d("TOTAL_ITEMS", "827")
                .d("PRODUCTS_COST", "1024")
                .d("DELIVERY_INCLUDED", "true")
            .and().insertInto("CONTACTS", 211L)
                .d("PHONE", "\"q>8\"")
                .d("ADDRESS", "\"UcUkUtaUW\"")
                .d("CITY_REGION", "\"WO7w6ZR8NH\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault100. HTTP Status 500. market/dto/assembler/UserAccountDtoAssembler_16_toModel GET:/customer
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> Response status 500 not defined for path '/customer'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer?included=NgAC")
                .then()
                .statusCode(500)// market/dto/assembler/UserAccountDtoAssembler_16_toModel
                .assertThat()
                .contentType("application/json")
                .body("'message'", nullValue())
                .body("'description'", containsString("uri=/customer"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * 1 - (404) GET:/customer/orders/{orderId}
    * 2 - (500) PUT:/customer/contacts
    * 3 - (406) PUT:/customer/contacts
    * 4 - (200) GET:/customer
    * Found 8 potential faults. Type-codes: 100, 200
    */
    @Test(timeout = 60000)
    public void test_7_getOnCustomerShowsFaults_100_200() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 209L)
                .d("ID", "65536")
                .d("USER_ACCOUNT_ID", "952")
                .d("DATE_CREATED", "\"2016-12-04\"")
                .d("EXECUTED", "true")
                .d("PRODUCTS_COST", "NULL")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "8996")
            .and().insertInto("CART", 210L)
                .d("TOTAL_ITEMS", "827")
                .d("PRODUCTS_COST", "1024")
                .d("DELIVERY_INCLUDED", "true")
            .and().insertInto("CONTACTS", 211L)
                .d("PHONE", "\"q>8\"")
                .d("ADDRESS", "\"UcUkUtaUW\"")
                .d("CITY_REGION", "\"WO7w6ZR8NH\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders/{orderId} -> No response body is expected but one was found.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/orders/4611686018427387904?name=a82QV7")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Requested entity doesn't exist"))
                .body("'description'", containsString("uri=/customer/orders/4611686018427387904"))
                .body("'entityName'", containsString("OrderDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("id"))
                .body("'fieldErrors'[0].'message'", containsString("No instance with this id"));
        
        // Fault100. HTTP Status 500. market/rest/exception/RestErrorResponse_50_getFieldErrors PUT:/customer/contacts
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/contacts -> Response status 500 not defined for path '/customer/contacts'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"_links\": [ " + 
                    " { " + 
                    " \"href\": \"GBLECDvHqdCK\", " + 
                    " \"hreflang\": \"s\", " + 
                    " \"media\": \"cCXQjNO\", " + 
                    " \"name\": \"PR4G4\", " + 
                    " \"profile\": \"N4rg\", " + 
                    " \"title\": \"3gUKxGTORu7n\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"70lAVBv\", " + 
                    " \"media\": \"oJ1RPYthB\", " + 
                    " \"profile\": \"bM3Ha\", " + 
                    " \"title\": \"4h\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"xzC4\", " + 
                    " \"hreflang\": \"0YoAmE7BVYY\", " + 
                    " \"name\": \"yL0KSl8TYs\", " + 
                    " \"profile\": \"tTDsKdHlyElvaF\" " + 
                    " }, " + 
                    " { " + 
                    " \"deprecation\": \"vLyqdQOtI7Ay\", " + 
                    " \"href\": \"p0DeQvJ_\", " + 
                    " \"name\": \"PO4oQ0\", " + 
                    " \"title\": \"9vo5M8pAjL69v_s\" " + 
                    " }, " + 
                    " { " + 
                    " \"hreflang\": \"2uWzubpgJ\", " + 
                    " \"profile\": \"eHJS\", " + 
                    " \"rel\": { " + 
                    " \"EM_tainted_map\": \"_EM_1_XYZ_\" " + 
                    " } " + 
                    " } " + 
                    " ], " + 
                    " \"address\": \"a\", " + 
                    " \"phone\": \"\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/contacts?name=_EM_1537_XYZ_")
                .then()
                .statusCode(500)// market/rest/exception/RestErrorResponse_50_getFieldErrors
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("JSON parse error: Expected relation name; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Expected relation name\n at [Source: (ByteArrayInputStream); line: 1, column: 13] (through reference chain: market.dto.ContactsDTO[\"_links\"])"))
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/contacts -> Response status 406 not defined for path '/customer/contacts'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"address\": \"UHBkIr686RZOR6p\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/contacts?name=_EM_1537_XYZ_")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", containsString("contactsDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("phone"))
                .body("'fieldErrors'[0].'message'", containsString("The value shall not be empty"));
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Manage contacts","Shopping cart"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/email'] ECMA 262 regex "^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]+$" does not match input string "admin"
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/name'] ECMA 262 regex "^[\pL '-]+$" does not match input string "Admin"
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/phone'] ECMA 262 regex "^\+[1-9][0-9]?[\s]*\(?\d{3}\)?[-\s]?\d{3}[-\s]?\d{2}[-\s]?\d{2}$" does not match input string "q>8"
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer?included=NgAC")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'email'", containsString("admin"))
                .body("'password'", containsString("hidden"))
                .body("'name'", containsString("Admin"))
                .body("'phone'", containsString("q>8"))
                .body("'address'", containsString("UcUkUtaUW"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/contacts
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_8_getOnContactsReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/contacts -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Shopping cart"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/contacts?name=yA3")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'phone'", containsString("+7 123 456 78 90"))
                .body("'address'", containsString("Riesstrasse 18"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/contacts
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_9_getOnContactsReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/contacts -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Shopping cart"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/contacts?included=iU1weK5bmQ6Ct")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'phone'", containsString("+7 123 456 78 90"))
                .body("'address'", containsString("Riesstrasse 18"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer
    * Found 2 potential faults of type-code 200
    */
    @Test(timeout = 60000)
    public void test_10_getOnCustomerReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Manage contacts","Shopping cart"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/name'] ECMA 262 regex "^[\pL '-]+$" does not match input string "Ivan Petrov"
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .header("X-Requested-With", "_EM_2966_XYZ_")
                .get(baseUrlOfSut + "/customer?name=15+y.o.")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'email'", containsString("ivan.petrov@yandex.ru"))
                .body("'password'", containsString("hidden"))
                .body("'name'", containsString("Ivan Petrov"))
                .body("'phone'", containsString("+7 123 456 78 90"))
                .body("'address'", containsString("Riesstrasse 18"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer
    * Found 2 potential faults of type-code 200
    */
    @Test(timeout = 60000)
    public void test_11_getOnCustomerWithQueryParamEmptyIncludedReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CART", 558L)
                .d("TOTAL_ITEMS", "749")
                .d("PRODUCTS_COST", "NULL")
                .d("DELIVERY_INCLUDED", "true")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Manage contacts","Shopping cart"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/name'] ECMA 262 regex "^[\pL '-]+$" does not match input string "Ivan Petrov"
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer?included=")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'email'", containsString("ivan.petrov@yandex.ru"))
                .body("'password'", containsString("hidden"))
                .body("'name'", containsString("Ivan Petrov"))
                .body("'phone'", containsString("+7 123 456 78 90"))
                .body("'address'", containsString("Riesstrasse 18"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/products/{productId}
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_12_getOnProductReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products/{productId} -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["All products"]
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/products/3?EMextraParam123=_EM_564_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'productId'", numberMatches(3.0))
                .body("'distillery'", containsString("Balvenie"))
                .body("'name'", containsString("12 y.o. Doublewood"))
                .body("'price'", numberMatches(5403.0))
                .body("'age'", numberMatches(12.0))
                .body("'volume'", numberMatches(700.0))
                .body("'alcohol'", numberMatches(40.0))
                .body("'description'", containsString("Has clear influences from both bourbon and sherry wood. This malt has only 12 years aged in bourbon casks and then 3 months in young Oloroso casks. The peppery character from the bourbon barrels, penetrates, as it were by the rich and full aroma of Oloroso casks it. The Balvenie Double Wood is therefore a very complex malt."))
                .body("'available'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/orders
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_13_getOnOrdersReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("USER_ROLE", 915L)
                .d("USER_ID", "766")
                .d("ROLE_ID", "NULL")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders -> [Path '/0'] Object instance has properties which are not allowed by the schema: ["links"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/orders?" + 
                    "name=HWSzm&" + 
                    "included=SUaYYuvv")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(1))
                .body("[0].'userAccount'", containsString("ivan.petrov@yandex.ru"))
                .body("[0].'billNumber'", numberMatches(2.7132054E8))
                .body("[0].'dateCreated'", containsString("2019-12-27T03:00:00.000+00:00"))
                .body("[0].'productsCost'", numberMatches(8127.0))
                .body("[0].'deliveryCost'", numberMatches(400.0))
                .body("[0].'deliveryIncluded'", equalTo(true))
                .body("[0].'totalCost'", numberMatches(8527.0))
                .body("[0].'payed'", equalTo(true))
                .body("[0].'executed'", equalTo(false))
                .body("[0].'links'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/orders
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_14_getOnCustomerOrdersWithQueryParamReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 412L)
                .d("ID", "660")
                .d("USER_ACCOUNT_ID", "-4742038828442035200")
                .d("DATE_CREATED", "\"2088-08-24\"")
                .d("EXECUTED", "false")
                .d("PRODUCTS_COST", "904")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "400")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders -> [Path '/0'] Object instance has properties which are not allowed by the schema: ["links"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/orders?included=_EM_2091_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(1))
                .body("[0].'userAccount'", containsString("ivan.petrov@yandex.ru"))
                .body("[0].'billNumber'", numberMatches(2.7132054E8))
                .body("[0].'dateCreated'", containsString("2019-12-27T03:00:00.000+00:00"))
                .body("[0].'productsCost'", numberMatches(8127.0))
                .body("[0].'deliveryCost'", numberMatches(400.0))
                .body("[0].'deliveryIncluded'", equalTo(true))
                .body("[0].'totalCost'", numberMatches(8527.0))
                .body("[0].'payed'", equalTo(true))
                .body("[0].'executed'", equalTo(false))
                .body("[0].'links'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/orders
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_15_getOnCustomerOrdersReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("PRODUCT", 605L)
                .d("NAME", "NULL")
                .d("DISTILLERY_ID", "806")
                .d("AGE", "NULL")
                .d("ALCOHOL", "0.8366927580306961")
                .d("VOLUME", "225")
                .d("PRICE", "0.8717805081414549")
                .d("DESCRIPTION", "\"YYNMMO9wsZ\"")
                .d("AVAILABLE", "false")
            .and().insertInto("CART", 606L)
                .d("TOTAL_ITEMS", "NULL")
                .d("PRODUCTS_COST", "492")
                .d("DELIVERY_INCLUDED", "true")
            .and().insertInto("CUSTOMER_ORDER", 607L)
                .d("ID", "688")
                .d("USER_ACCOUNT_ID", "NULL")
                .d("DATE_CREATED", "NULL")
                .d("EXECUTED", "true")
                .d("PRODUCTS_COST", "581")
                .d("DELIVERY_INCLUDED", "true")
                .d("DELIVERY_COST", "182")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders -> [Path '/0'] Object instance has properties which are not allowed by the schema: ["links"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/orders")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(1))
                .body("[0].'userAccount'", containsString("ivan.petrov@yandex.ru"))
                .body("[0].'billNumber'", numberMatches(2.7132054E8))
                .body("[0].'dateCreated'", containsString("2019-12-27T03:00:00.000+00:00"))
                .body("[0].'productsCost'", numberMatches(8127.0))
                .body("[0].'deliveryCost'", numberMatches(400.0))
                .body("[0].'deliveryIncluded'", equalTo(true))
                .body("[0].'totalCost'", numberMatches(8527.0))
                .body("[0].'payed'", equalTo(true))
                .body("[0].'executed'", equalTo(false))
                .body("[0].'links'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/products
    * Found 14 potential faults of type-code 200
    */
    @Test(timeout = 60000)
    public void test_16_getOnProductsReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("USER_ROLE", 788L)
                .d("USER_ID", "925")
                .d("ROLE_ID", "966")
            .and().insertInto("CONTACTS", 789L)
                .d("PHONE", "\"zZJgRwUXvQF6\"")
                .d("ADDRESS", "\"icSlrwRBgPXhMsk\"")
                .d("CITY_REGION", "\"PwwIZxY8ch0X\"")
            .and().insertInto("CUSTOMER_ORDER", 790L)
                .d("ID", "936")
                .d("USER_ACCOUNT_ID", "873")
                .d("DATE_CREATED", "\"1988-02-15\"")
                .d("EXECUTED", "false")
                .d("PRODUCTS_COST", "268")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "-2118472385")
            .and().insertInto("PRODUCT", 791L)
                .d("NAME", "\"Jngj8P\"")
                .d("DISTILLERY_ID", "NULL")
                .d("AGE", "341")
                .d("ALCOHOL", "-22.0195406493")
                .d("VOLUME", "66500")
                .d("PRICE", "0.6405947035721173")
                .d("DESCRIPTION", "\"t1FmjT1_TiTg__Z0\"")
                .d("AVAILABLE", "false")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/0'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/1'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/2'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/3'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/4'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/5'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/6'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/7'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/8'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/9'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/10'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/11'] Object instance has properties which are not allowed by the schema: ["links"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/11/alcohol'] Numeric instance is lower than the required minimum (minimum: 1, found: -22.01954)
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products -> [Path '/11/distillery'] Instance type (null) does not match any allowed primitive type (allowed: ["string"])
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/products")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(12))
                .body("[0].'productId'", numberMatches(1.0))
                .body("[0].'distillery'", containsString("Ardbeg"))
                .body("[0].'name'", containsString("Ten"))
                .body("[0].'price'", numberMatches(4420.0))
                .body("[0].'age'", numberMatches(10.0))
                .body("[0].'volume'", numberMatches(700.0))
                .body("[0].'alcohol'", numberMatches(46.0))
                .body("[0].'description'", containsString("Ten Years Old is the basis of the Ardbeg range. After 10 years of maturation in ex-bourbon casks, the whiskey bottled at 46% ABV without cold filtering. The characteristic peat, although clearly present but in perfect balance with the natural sweetness and not predominant in the taste."))
                .body("[0].'available'", equalTo(false))
                .body("[0].'links'.size()", equalTo(1))
                .body("[0].'links'[0].'rel'", containsString("self"))
                .body("[1].'productId'", numberMatches(2.0))
                .body("[1].'distillery'", containsString("Ardbeg"))
                .body("[1].'name'", containsString("Uigeadail"))
                .body("[1].'price'", numberMatches(7020.0))
                .body("[1].'age'", numberMatches(0.0))
                .body("[1].'volume'", numberMatches(700.0))
                .body("[1].'alcohol'", numberMatches(54.2))
                .body("[1].'description'", containsString("Ardbeg Uigedael is named after Loch Uigedael, the lake in the grounds of the distillery Ardbeg which are the water is an important factor in the distilling process. The Uigedael a vatted malt, bottled at 54.2% ABV without cold filtering. Ardbeg Uigedael has no age indication for the expression consists of various malts of different ages. Malts are used partly matured in ex-bourbon and partly on ex-sherry casks."))
                .body("[1].'available'", equalTo(true))
                .body("[1].'links'.size()", equalTo(1))
                .body("[1].'links'[0].'rel'", containsString("self"))
                .body("[2].'productId'", numberMatches(3.0))
                .body("[2].'distillery'", containsString("Balvenie"))
                .body("[2].'name'", containsString("12 y.o. Doublewood"))
                .body("[2].'price'", numberMatches(5403.0))
                .body("[2].'age'", numberMatches(12.0))
                .body("[2].'volume'", numberMatches(700.0))
                .body("[2].'alcohol'", numberMatches(40.0))
                .body("[2].'description'", containsString("Has clear influences from both bourbon and sherry wood. This malt has only 12 years aged in bourbon casks and then 3 months in young Oloroso casks. The peppery character from the bourbon barrels, penetrates, as it were by the rich and full aroma of Oloroso casks it. The Balvenie Double Wood is therefore a very complex malt."))
                .body("[2].'available'", equalTo(true))
                .body("[2].'links'.size()", equalTo(1))
                .body("[2].'links'[0].'rel'", containsString("self"))
                ; // Skipping assertions on the remaining 9 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_17_getOnCustomerCartWithQueryParamEmptyNameReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/cart -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/cart?name=")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("admin"))
                .body("'totalItems'", numberMatches(0.0))
                .body("'productsCost'", numberMatches(0.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(true))
                .body("'totalCost'", numberMatches(400.0))
                .body("'cartItems'.size()", equalTo(0))
                .body("'empty'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_18_deleteOnCartReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CONTACTS", 687L)
                .d("PHONE", "NULL")
                .d("ADDRESS", "NULL")
                .d("CITY_REGION", "NULL")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/customer/cart -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/customer/cart?included=yk8BOBHZZMWzW")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("admin"))
                .body("'totalItems'", numberMatches(0.0))
                .body("'productsCost'", numberMatches(0.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(true))
                .body("'totalCost'", numberMatches(400.0))
                .body("'cartItems'.size()", equalTo(0))
                .body("'empty'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_19_deleteOnCustomerCartWithQueryParamsReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("USER_ROLE", 305L)
                .d("USER_ID", "NULL")
                .d("ROLE_ID", "NULL")
            .and().insertInto("CONTACTS", 306L)
                .d("PHONE", "\"TuxGgo_GwMRF\"")
                .d("ADDRESS", "NULL")
                .d("CITY_REGION", "NULL")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/customer/cart -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/customer/cart?" + 
                    "name=j6x&" + 
                    "included=z1nN")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("admin"))
                .body("'totalItems'", numberMatches(0.0))
                .body("'productsCost'", numberMatches(0.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(true))
                .body("'totalCost'", numberMatches(400.0))
                .body("'cartItems'.size()", equalTo(0))
                .body("'empty'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_20_deleteOnCustomerCartReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CONTACTS", 700L)
                .d("PHONE", "\"4zFzqikaG\"")
                .d("ADDRESS", "NULL")
                .d("CITY_REGION", "\"Ff9enf_lIHscvat\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/customer/cart -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/customer/cart")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("admin"))
                .body("'totalItems'", numberMatches(0.0))
                .body("'productsCost'", numberMatches(0.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(true))
                .body("'totalCost'", numberMatches(400.0))
                .body("'cartItems'.size()", equalTo(0))
                .body("'empty'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) PUT:/customer/cart/delivery
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_21_putOnCartDeliveryWithQueryParamsReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart/delivery -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .put(baseUrlOfSut + "/customer/cart/delivery?" + 
                    "included=false&" + 
                    "name=_EM_155_XYZ_&" + 
                    "EMextraParam123=_EM_156_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("admin"))
                .body("'totalItems'", numberMatches(0.0))
                .body("'productsCost'", numberMatches(0.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(false))
                .body("'totalCost'", numberMatches(400.0))
                .body("'cartItems'.size()", equalTo(0))
                .body("'empty'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/cart
    * Found 2 potential faults of type-code 200
    */
    @Test(timeout = 60000)
    public void test_22_getOnCartReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/cart -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/cart -> [Path '/cartItems/0/_links'] Object instance has properties which are not allowed by the schema: ["View product"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/cart?included=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("ivan.petrov@yandex.ru"))
                .body("'totalItems'", numberMatches(1.0))
                .body("'productsCost'", numberMatches(6517.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(true))
                .body("'totalCost'", numberMatches(6917.0))
                .body("'cartItems'.size()", equalTo(1))
                .body("'cartItems'[0].'productId'", numberMatches(5.0))
                .body("'cartItems'[0].'quantity'", numberMatches(1.0))
                .body("'empty'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * 1 - (404) GET:/customer/orders/{orderId}
    * 2 - (200) GET:/customer
    * Found 5 potential faults of type-code 200
    */
    @Test(timeout = 60000)
    public void test_23_getOnCustomerReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 241L)
                .d("ID", "163")
                .d("USER_ACCOUNT_ID", "931")
                .d("DATE_CREATED", "NULL")
                .d("EXECUTED", "true")
                .d("PRODUCTS_COST", "270")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "665")
            .and().insertInto("CART", 242L)
                .d("TOTAL_ITEMS", "796")
                .d("PRODUCTS_COST", "NULL")
                .d("DELIVERY_INCLUDED", "false")
            .and().insertInto("CONTACTS", 243L)
                .d("PHONE", "NULL")
                .d("ADDRESS", "\"or\"")
                .d("CITY_REGION", "NULL")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders/{orderId} -> No response body is expected but one was found.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "_EM_1088_XYZ_")
                .get(baseUrlOfSut + "/customer/orders/28?" + 
                    "name=hxM4dPasxVxnu_&" + 
                    "EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Requested entity doesn't exist"))
                .body("'description'", containsString("uri=/customer/orders/28"))
                .body("'entityName'", containsString("OrderDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("id"))
                .body("'fieldErrors'[0].'message'", containsString("No instance with this id"));
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Manage contacts","Shopping cart"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/email'] ECMA 262 regex "^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]+$" does not match input string "admin"
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/name'] ECMA 262 regex "^[\pL '-]+$" does not match input string "Admin"
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> [Path '/phone'] Instance type (null) does not match any allowed primitive type (allowed: ["string"])
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer?EMextraParam123=42")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'email'", containsString("admin"))
                .body("'password'", containsString("hidden"))
                .body("'name'", containsString("Admin"))
                .body("'phone'", nullValue())
                .body("'address'", containsString("or"));
    }
    
    
    /**
    * Calls:
    * (200) PUT:/customer/cart/delivery
    * Found 2 potential faults of type-code 200
    */
    @Test(timeout = 60000)
    public void test_24_putOnDeliveryReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart/delivery -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart/delivery -> [Path '/cartItems/0/_links'] Object instance has properties which are not allowed by the schema: ["View product"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .put(baseUrlOfSut + "/customer/cart/delivery?" + 
                    "included=true&" + 
                    "name=_EM_297_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("ivan.petrov@yandex.ru"))
                .body("'totalItems'", numberMatches(1.0))
                .body("'productsCost'", numberMatches(6517.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(true))
                .body("'totalCost'", numberMatches(6917.0))
                .body("'cartItems'.size()", equalTo(1))
                .body("'cartItems'[0].'productId'", numberMatches(5.0))
                .body("'cartItems'[0].'quantity'", numberMatches(1.0))
                .body("'empty'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * (200) PUT:/customer/cart/delivery
    * Found 2 potential faults of type-code 200
    */
    @Test(timeout = 60000)
    public void test_25_putOnCartDeliveryWithQueryParamIncludedReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart/delivery -> [Path '/_links'] Object instance has properties which are not allowed by the schema: ["Customer contacts","Proceed to payment"]
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart/delivery -> [Path '/cartItems/0/_links'] Object instance has properties which are not allowed by the schema: ["View product"]
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "42")
                .put(baseUrlOfSut + "/customer/cart/delivery?included=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'user'", containsString("ivan.petrov@yandex.ru"))
                .body("'totalItems'", numberMatches(1.0))
                .body("'productsCost'", numberMatches(6517.0))
                .body("'deliveryCost'", numberMatches(400.0))
                .body("'deliveryIncluded'", equalTo(true))
                .body("'totalCost'", numberMatches(6917.0))
                .body("'cartItems'.size()", equalTo(1))
                .body("'cartItems'[0].'productId'", numberMatches(5.0))
                .body("'cartItems'[0].'quantity'", numberMatches(1.0))
                .body("'empty'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_26_getOnCustomerReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401.0))
                .body("'error'", containsString("Unauthorized"))
                .body("'message'", containsString(""))
                .body("'path'", containsString("/customer"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_27_getOnCartReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/cart -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/cart?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Access is denied"))
                .body("'description'", containsString("uri=/customer/cart"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_28_deleteOnCartReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/customer/cart -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .delete(baseUrlOfSut + "/customer/cart?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Access is denied"))
                .body("'description'", containsString("uri=/customer/cart"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/contacts
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_29_getOnCustomerContactsWithQueryParamsReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/contacts -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/customer/contacts?" + 
                    "name=_EM_5_XYZ_&" + 
                    "EMextraParam123=_EM_6_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Access is denied"))
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/orders
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_30_getOnOrdersReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_9_XYZ_")
                .get(baseUrlOfSut + "/customer/orders?" + 
                    "name=_EM_7_XYZ_&" + 
                    "EMextraParam123=_EM_8_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Access is denied"))
                .body("'description'", containsString("uri=/customer/orders"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/orders/{orderId}
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_31_getOnOrderReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders/{orderId} -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/customer/orders/-2116781?name=LtUc4Hepd4gr")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Access is denied"))
                .body("'description'", containsString("uri=/customer/orders/-2116781"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (401) PUT:/customer/cart/delivery
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_32_putOnDeliveryReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart/delivery -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .put(baseUrlOfSut + "/customer/cart/delivery?" + 
                    "included=true&" + 
                    "name=_EM_24_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Access is denied"))
                .body("'description'", containsString("uri=/customer/cart/delivery"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (401) PUT:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_33_putOnCartReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart -> No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"productId\": 513, " + 
                    " \"quantity\": 703 " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/cart?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Access is denied"))
                .body("'description'", containsString("uri=/customer/cart"))
                .body("'entityName'", nullValue())
                .body("'fieldErrors'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (404) GET:/customer/orders/{orderId}
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_34_getOnCustomerOrderReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders/{orderId} -> No response body is expected but one was found.
        given().accept("*/*")
                .header("Authorization", "Basic dXNlcjJAeWFuZGV4LnJ1Onl1cmlkb2xnb3J1a2k=") // user2
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/orders/30")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Requested entity doesn't exist"))
                .body("'description'", containsString("uri=/customer/orders/30"))
                .body("'entityName'", containsString("OrderDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("id"))
                .body("'fieldErrors'[0].'message'", containsString("No instance with this id"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/products/{productId}
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_35_getOnProductReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products/{productId} -> No response body is expected but one was found.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/products/-7327916939553816866?EMextraParam123=_EM_643_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Requested entity doesn't exist"))
                .body("'description'", containsString("uri=/products/-7327916939553816866"))
                .body("'entityName'", containsString("ProductDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("id"))
                .body("'fieldErrors'[0].'message'", containsString("No instance with this id"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/products/{productId}
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_36_getOnProductReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 209L)
                .d("ID", "0")
                .d("USER_ACCOUNT_ID", "952")
                .d("DATE_CREATED", "\"2016-12-04\"")
                .d("EXECUTED", "false")
                .d("PRODUCTS_COST", "962")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "0")
            .and().insertInto("CART", 210L)
                .d("TOTAL_ITEMS", "-523461")
                .d("PRODUCTS_COST", "1115136")
                .d("DELIVERY_INCLUDED", "false")
            .and().insertInto("CONTACTS", 211L)
                .d("PHONE", "\"_EM_3448_XYZ_\"")
                .d("ADDRESS", "\"U[UkUtaUWZ\"")
                .d("CITY_REGION", "\"WO7w6ZR8ND\"")
            .and().insertInto("PRODUCT", 584L)
                .d("NAME", "\"ypTD\"")
                .d("DISTILLERY_ID", "777")
                .d("AGE", "51")
                .d("ALCOHOL", "0.709626379638566")
                .d("VOLUME", "324")
                .d("PRICE", "0.0")
                .d("DESCRIPTION", "\"U\"")
                .d("AVAILABLE", "false")
            .and().insertInto("USER_ACCOUNT", 651L)
                .d("EMAIL", "\"hAiwVW\"")
                .d("PASSWORD", "NULL")
                .d("NAME", "\"gc\"")
                .d("ACTIVE", "false")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/products/{productId} -> No response body is expected but one was found.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/products/884774016")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Requested entity doesn't exist"))
                .body("'description'", containsString("uri=/products/884774016"))
                .body("'entityName'", containsString("ProductDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("id"))
                .body("'fieldErrors'[0].'message'", containsString("No instance with this id"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/customer/orders/{orderId}
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_37_getOnOrderReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("USER_ROLE", 788L)
                .d("USER_ID", "925")
                .d("ROLE_ID", "966")
            .and().insertInto("CONTACTS", 789L)
                .d("PHONE", "\"zZJgRwUXvQF6\"")
                .d("ADDRESS", "\"icSlrwRBgPXhMsk\"")
                .d("CITY_REGION", "\"PwwIZxY8ch0X\"")
            .and().insertInto("CUSTOMER_ORDER", 790L)
                .d("ID", "936")
                .d("USER_ACCOUNT_ID", "873")
                .d("DATE_CREATED", "\"1988-02-15\"")
                .d("EXECUTED", "false")
                .d("PRODUCTS_COST", "268")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "-2118472385")
            .and().insertInto("PRODUCT", 791L)
                .d("NAME", "\"Jngj8P\"")
                .d("DISTILLERY_ID", "NULL")
                .d("AGE", "341")
                .d("ALCOHOL", "-22.0195406493")
                .d("VOLUME", "66500")
                .d("PRICE", "0.6405947035721173")
                .d("DESCRIPTION", "\"t1FmjT1_TiTg__Z0\"")
                .d("AVAILABLE", "false")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/customer/orders/{orderId} -> No response body is expected but one was found.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/customer/orders/846?included=R7ljDPGh")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Requested entity doesn't exist"))
                .body("'description'", containsString("uri=/customer/orders/846"))
                .body("'entityName'", containsString("OrderDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("id"))
                .body("'fieldErrors'[0].'message'", containsString("No instance with this id"));
    }
    
    
    /**
    * Calls:
    * (404) PUT:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_38_putOnCartReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart -> No response body is expected but one was found.
        given().accept("*/*")
                .header("Authorization", "Basic dXNlcjJAeWFuZGV4LnJ1Onl1cmlkb2xnb3J1a2k=") // user2
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"productId\": 122, " + 
                    " \"quantity\": 654 " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/cart?name=va")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Requested entity doesn't exist"))
                .body("'description'", containsString("uri=/customer/cart"))
                .body("'entityName'", containsString("Product"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("id"))
                .body("'fieldErrors'[0].'message'", containsString("No instance with this id"));
    }
    
    
    /**
    * Calls:
    * (406) POST:/customer/cart/pay
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_39_postOnPayReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/customer/cart/pay -> Response status 406 not defined for path '/customer/cart/pay'.
        given().accept("*/*")
                .header("Authorization", "Basic dXNlcjJAeWFuZGV4LnJ1Onl1cmlkb2xnb3J1a2k=") // user2
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"ccNumber\": \"_postfix\" " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/cart/pay?included=3O3ZjAHrHq")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/customer/cart/pay"))
                .body("'entityName'", containsString("creditCardDTO"))
                .body("'fieldErrors'.size()", equalTo(2))
                .body("'fieldErrors'[0].'field'", containsString("ccNumber"))
                .body("'fieldErrors'[0].'message'", containsString("Not a valid credit card number"))
                .body("'fieldErrors'[1].'field'", containsString("ccNumber"))
                .body("'fieldErrors'[1].'message'", containsString("Card number shall consist of 13-16 digits"));
    }
    
    
    /**
    * Calls:
    * (406) POST:/register
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_40_postOnRegisterWithQueryParamReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/register -> Response status 406 not defined for path '/register'.
        given().accept("*/*")
                .header("Authorization", "Basic dXNlcjJAeWFuZGV4LnJ1Onl1cmlkb2xnb3J1a2k=") // user2
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"eP1bC4GFQ_U5q\", " + 
                    " \"name\": \"\u0027 L\", " + 
                    " \"phone\": \"_postfix\" " + 
                    " } ")
                .post(baseUrlOfSut + "/register?included=ggOMNTh7RdhdFj9")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/register"))
                .body("'entityName'", containsString("userDTO"))
                .body("'fieldErrors'.size()", equalTo(3))
                .body("'fieldErrors'[0].'field'", containsString("address"))
                .body("'fieldErrors'[0].'message'", containsString("The value shall not be empty"))
                .body("'fieldErrors'[1].'field'", containsString("email"))
                .body("'fieldErrors'[1].'message'", containsString("The value shall be in the format of an email address"))
                .body("'fieldErrors'[2].'field'", containsString("phone"))
                .body("'fieldErrors'[2].'message'", containsString("Shall consist of a + sign, a country code, a region code (1-4 digits), and a number (6-7 digits)"));
    }
    
    
    /**
    * Calls:
    * (406) POST:/customer/cart/pay
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_41_postOnPayReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CONTACTS", 664L)
                .d("PHONE", "NULL")
                .d("ADDRESS", "\"A4ypZStTUR\"")
                .d("CITY_REGION", "NULL")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/customer/cart/pay -> Response status 406 not defined for path '/customer/cart/pay'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/customer/cart/pay?name=7Milw0jLlbdhAaml")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/customer/cart/pay"))
                .body("'entityName'", containsString("creditCardDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("ccNumber"))
                .body("'fieldErrors'[0].'message'", containsString("The value shall not be empty"));
    }
    
    
    /**
    * Calls:
    * (406) PUT:/customer/contacts
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_42_putOnContactsReturnsSchemaInvalidResponse() throws Exception {
        List<InsertionDto> insertions = sql().insertInto("CUSTOMER_ORDER", 209L)
                .d("ID", "65536")
                .d("USER_ACCOUNT_ID", "952")
                .d("DATE_CREATED", "\"2016-12-04\"")
                .d("EXECUTED", "false")
                .d("PRODUCTS_COST", "NULL")
                .d("DELIVERY_INCLUDED", "false")
                .d("DELIVERY_COST", "8996")
            .and().insertInto("CART", 210L)
                .d("TOTAL_ITEMS", "827")
                .d("PRODUCTS_COST", "1024")
                .d("DELIVERY_INCLUDED", "true")
            .and().insertInto("CONTACTS", 211L)
                .d("PHONE", "\"q>8\"")
                .d("ADDRESS", "\"UcUkUtaUW\"")
                .d("CITY_REGION", "\"WO7w6ZR8NH\"")
            .dtos();
        InsertionResultsDto insertionsresult = controller.execInsertionsIntoDatabase(insertions);
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/contacts -> Response status 406 not defined for path '/customer/contacts'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"address\": \"A0g\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/contacts?name=aTyvS")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/customer/contacts"))
                .body("'entityName'", containsString("contactsDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("phone"))
                .body("'fieldErrors'[0].'message'", containsString("The value shall not be empty"));
    }
    
    
    /**
    * Calls:
    * (406) POST:/register
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_43_postOnRegisterReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/register -> Response status 406 not defined for path '/register'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"\u0027\", " + 
                    " \"password\": \"LY\", " + 
                    " \"phone\": \"_postfix\" " + 
                    " } ")
                .post(baseUrlOfSut + "/register")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/register"))
                .body("'entityName'", containsString("userDTO"))
                .body("'fieldErrors'.size()", equalTo(4))
                .body("'fieldErrors'[0].'field'", containsString("address"))
                .body("'fieldErrors'[0].'message'", containsString("The value shall not be empty"))
                .body("'fieldErrors'[1].'field'", containsString("phone"))
                .body("'fieldErrors'[1].'message'", containsString("Shall consist of a + sign, a country code, a region code (1-4 digits), and a number (6-7 digits)"))
                .body("'fieldErrors'[2].'field'", containsString("email"))
                .body("'fieldErrors'[2].'message'", containsString("The value shall not be empty"))
                ; // Skipping assertions on the remaining 1 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (406) POST:/register
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_44_postOnRegisterReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/register -> Response status 406 not defined for path '/register'.
        given().accept("*/*")
                .header("Authorization", "Basic aXZhbi5wZXRyb3ZAeWFuZGV4LnJ1OnBldHJvdg==") // user
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"address\": \"L4ZGkZ50Y10\", " + 
                    " \"email\": \"_EM_3391_XYZ_\", " + 
                    " \"phone\": \"_postfix\" " + 
                    " } ")
                .post(baseUrlOfSut + "/register")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/register"))
                .body("'entityName'", containsString("userDTO"))
                .body("'fieldErrors'.size()", equalTo(3))
                .body("'fieldErrors'[0].'field'", containsString("email"))
                .body("'fieldErrors'[0].'message'", containsString("The value shall be in the format of an email address"))
                .body("'fieldErrors'[1].'field'", containsString("name"))
                .body("'fieldErrors'[1].'message'", containsString("The value shall not be empty"))
                .body("'fieldErrors'[2].'field'", containsString("phone"))
                .body("'fieldErrors'[2].'message'", containsString("Shall consist of a + sign, a country code, a region code (1-4 digits), and a number (6-7 digits)"));
    }
    
    
    /**
    * Calls:
    * (406) PUT:/customer/cart
    * Found 1 potential fault of type-code 200
    */
    @Test(timeout = 60000)
    public void test_45_putOnCustomerCartReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/customer/cart -> Response status 406 not defined for path '/customer/cart'.
        given().accept("*/*")
                .header("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=") // admin
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"productId\": -598337516, " + 
                    " \"quantity\": 114 " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/cart")
                .then()
                .statusCode(406)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Argument validation error"))
                .body("'description'", containsString("uri=/customer/cart"))
                .body("'entityName'", containsString("cartItemDTO"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'[0].'field'", containsString("productId"))
                .body("'fieldErrors'[0].'message'", containsString("Value shall be a positive number"));
    }


}
